theme: jekyll-theme-dinky
title: [Suprived Learning Classifier Using R Shiny]
<! --- description: [This app allows users to explore mammographic mass data and fit models for predicting mass status through repeated cross-validated supervised learning models.] --- >
